apiVersion: v1
kind: ConfigMap
metadata:
  name: console-consumer-jmxexporter-config
data:
  config.yml: |+
    ---
    hostPort: localhost:9010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
    name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
        name: kafka-consumer
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: kafka-consumer
          image: wurstmeister/kafka:2.12-2.2.0
          command: ["/opt/kafka/bin/kafka-console-consumer.sh", "--topic", "orders", "--bootstrap-server", "http://kafka:9092"]
          env:
            - { name: KAFKA_JMX_OPTS,                       value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9010" }
            - { name: JMX_PORT,                             value: "9010" }
          resources:
            requests: { memory: "100Mi" }
            limits:   { memory: "200Mi" }
          ports:
            - { name: jmx-port, containerPort: 9010, protocol: TCP }
          volumeMounts:
            - {name: tmp,    mountPath: /tmp }
            - {name: vartmp, mountPath: /var/tmp }
        - name: "jmx-exporter"
          image: sscaling/jmx-prometheus-exporter
          ports:
           - { containerPort: 5556, name: metrics, protocol: TCP }
          env:
           - { name: JVM_OPTS,                    value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1" }
          volumeMounts:
           - name: console-consumer-jmxexporter-config
             mountPath: /opt/jmx_exporter/config.yml
             subPath: config.yml
      volumes:
        - { name: tmp,    emptyDir: {} }
        - { name: vartmp, emptyDir: {} }
        - { name: console-consumer-jmxexporter-config, configMap: { name: console-consumer-jmxexporter-config, defaultMode: 0744 } }