apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-consumer-jmxexporter-config
data:
  config.yml: |+
    ---
    hostPort: localhost:9999
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-consumer
spec:
  template:
    metadata:
      labels:
        name: orders-consumer
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      containers:
        - name: orders-consumer
          image: jeroenrosenberg/order-consumer:0.1.0-SNAPSHOT
          imagePullPolicy: Always
          resources:
            requests: { memory: "300Mi" }
            limits:   { memory: "300Mi" }
          env:
            - { name: "JAVA_OPTS",                            value: "-Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false" }
        - name: "jmx-exporter"
          image: sscaling/jmx-prometheus-exporter
          ports:
           - { containerPort: 5556, name: metrics, protocol: TCP }
          env:
           - { name: JVM_OPTS,                    value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1" }
          volumeMounts:
           - name: orders-consumer-jmxexporter-config
             mountPath: /opt/jmx_exporter/config.yml
             subPath: config.yml
      volumes:
        - { name: orders-consumer-jmxexporter-config, configMap: { name: orders-consumer-jmxexporter-config, defaultMode: 0744 }}
  replicas: 1
  selector:
    matchLabels:
      name: orders-consumer